### ISSUE TITLE
Übersetzung der Antivirus Fehlermeldungen anpassen

### ISSUE THREAD

**Issue by Kagemaru** [stadtluzern/decidim-ocl#166]
EN keys:
```yaml
  errors:
    messages:
      antivirus_virus_detected: 'contains a virus'
      antivirus_client_error: 'could not be processed for virus scan'
      antivirus_file_not_found: 'could not be found for virus scan'
```

DE keys:
```yaml
  errors:
    messages:
      antivirus_virus_detected: 'enthält einen Virus'
      antivirus_client_error: 'kann nicht gescannt werden'
      antivirus_file_not_found: 'wurde nicht gefunden'
```
