### ISSUE TITLE
Term Customizer greift in Mails nicht.

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#225]

**Comment by Naadjjaa** [comment]
Trotz Übersetzung im Term Customizer gehen Mails seit dem Upgrade in der Sie Form raus und mit alten Begriffen. 
![image](https://user-images.githubusercontent.com/75797851/188817782-d2912424-185d-425b-9ded-f2f28c79b4eb.png)

**Comment by Naadjjaa** [comment]
@bsantschi Ich wäre froh ihr könntet dies anschauen. Ich erhalte bereits Beschwerdemails wegen der unschönen Benachrichtigungen.

**Comment by Kagemaru** [comment]
Ich bin dies momentan am Nachstellen.

**Comment by Kagemaru** [comment]
Ich habe unser Problem bei TermCustomizer als Issue erstellt:
https://github.com/mainio/decidim-module-term_customizer/issues/93

**Comment by bsantschi** [comment]
Bis der [Fehler bei TermCustomizer](https://github.com/mainio/decidim-module-term_customizer/issues/93) geflickt wird, könnten wir das Problem umgehen, indem wir generische/gemeinsame E-Mailtitel für alle Tenants definieren. Die E-Mail-Inhalte sollten wir pro Tenant unterschiedlich machen können, jedoch nicht im TermCustomizer, sondern direkt im Code. Folgende Übersetzungen sind davon betroffen:

`{:confirmation_instructions=>{:action=>"Bestätige mein Konto", :greeting=>"Willkommen %{recipient}!", :instruction=>"Sie können Ihre Konto-E-Mail über den folgenden Link bestätigen:", :subject=>"Open Community Luzern: E-Mail bestätigen"},
 :email_changed=>{:greeting=>"Hallo %{recipient}!", :message=>"Wir setzen uns mit Ihnen in Verbindung, um Sie darüber zu informieren, dass Ihre E-Mail-Adresse auf %{email}geändert wird.", :message_unconfirmed=>"Wir schreiben Ihnen, um Sie darüber zu informieren, dass Ihre E-Mail-Adresse zu %{email} geändert wird.", :subject=>"E-Mail geändert"},
 :password_change=>{:greeting=>"Hallo %{recipient}!", :message=>"Wir kontaktieren Sie, um Sie darüber zu informieren, dass Ihr Passwort geändert wurde.", :subject=>"Passwort geändert"},
 :reset_password_instructions=>
  {:action=>"Mein Passwort ändern",
   :greeting=>"Hallo %{recipient}!",
   :instruction=>"Jemand hat einen Link angefordert, um dein Passwort zu ändern. Falls du das selbst warst, dann folge diesem Link:",
   :instruction_2=>"Falls du das nicht selbst warst, kannst du diese E-Mail ignorieren.",
   :instruction_3=>"Dein Passwort ändert sich erst, wenn du auf den obigen Link zugreifst und ein neues Passwort erstellst.",
   :subject=>"Passwort zurücksetzen"},
 :unlock_instructions=>{:action=>"Entsperren Sie mein Konto", :greeting=>"Hallo %{recipient}!", :instruction=>"Klicken Sie auf den folgenden Link, um Ihr Konto zu entsperren:", :message=>"Ihr Konto wurde aufgrund einer übermäßigen Anzahl fehlgeschlagener Anmeldeversuche gesperrt.", :subject=>"Entsperren Anweisungen"},
 :invitation_instructions=>
  {:subject=>"Anweisungen zur Einladung",
   :hello=>"Hallo %{email}",
   :someone_invited_you=>"Jemand hat dich zu %{application}eingeladen. Sie können es über den folgenden Link akzeptieren.",
   :accept=>"Die Einladung annehmen",
   :accept_until=>"Diese Einladung wird in %{due_date}fällig.",
   :ignore=>"Wenn Sie die Einladung nicht annehmen möchten, ignorieren Sie diese E-Mail.<br />\nIhr Konto wird erst erstellt, wenn Sie auf den obigen Link zugreifen und Ihren Benutzernamen und Ihr Passwort festlegen.",
   :decline=>"Einladung ablehnen",
   :invited_you_as_admin=>"%{invited_by} hat dich als Admin von %{application}eingeladen. Sie können es über den folgenden Link akzeptieren.",
   :invited_you_as_private_user=>"%{invited_by} hat dich als privaten Benutzer von %{application}eingeladen. Sie können es über den folgenden Link akzeptieren.",
   :someone_invited_you_as_admin=>"Jemand hat dich als Admin von %{application}eingeladen, du kannst es über den untenstehenden Link akzeptieren.",
   :someone_invited_you_as_private_user=>"Jemand hat dich als private_user von %{application}eingeladen, du kannst es über den folgenden Link akzeptieren."},
 :invite_admin=>{:subject=>"Du wurdest eingeladen, %{organization} zu verwalten"},
 :invite_collaborator=>{:subject=>"Du wurdest eingeladen, an %{organization}"},
 :invite_private_user=>{:subject=>"Du wurdest zu einem privaten Partizipationsprozess auf %{organization} eingeladen"},
 :organization_admin_invitation_instructions=>{:subject=>"Du wurdest eingeladen, %{organization} zu verwalten"},
 :join_meeting=>{:subject=>"Einladung, an einem Meeting teilzunehmen"},
 :join_conference=>{:subject=>"Einladung zur Teilnahme an einer Konferenz"}}`

**Comment by Naadjjaa** [comment]
[E-Mail Notifications.csv](https://github.com/stadtluzern/decidim-ocl/files/9654644/E-Mail.Notifications.csv)
@Kagemaru hier die Datei mit allen Übersetzungen der E-Mail Benachrichtigungen

**Comment by Kagemaru** [comment]
@Naadjjaa:
Die  Übersetzungen habe ich mal so auf INT deployed.
Folgende Keys wurden verwendet:
```yaml
--- 
devise: 
  mailer: 
    confirmation_instructions: 
      action: "Bestätige dein Konto"
      greeting: "Willkommen %{recipient}!"
      instruction: "Du kannst deine E-Mail-Adresse über den folgenden Link bestätigen:"
    email_changed: 
      greeting: "Hallo %{recipient}!"
      message: "Wir schreiben dir, um dich darüber zu informieren, dass deine E-Mail-Adresse zu %{email} geändert wurde."
      message_unconfirmed: "Wir schreiben dir, um dich darüber zu informieren, dass deine E-Mail-Adresse zu %{email} geändert wurde."
    invitation_instructions: 
      accept: "Die Einladung annehmen"
      accept_until: "Diese Einladung wird in %{due_date} fällig."
      decline: "Einladung ablehnen"
      hello: "Hallo %{email},"
      ignore: "Wenn du die Einladung nicht annehmen möchtest, ignoriere diese E-Mail.<br /> Dein Konto wird erst erstellt, Wenn du auf den obigen Link zugreifst und deinen Benutzernamen und dein Passwort festlegst."
      invited_you_as_admin: "%{invited_by} hat dich als Admin von %{application} eingeladen. Du kannst es über den folgenden Link akzeptieren."
      invited_you_as_private_user: "%{invited_by} hat dich als private/n Benutzer/in von %{application} eingeladen. Du kannst es über den folgenden Link akzeptieren."
      someone_invited_you: "Jemand hat dich zu %{application} eingeladen. Du kannst die Einladung über den folgenden Link akzeptieren."
      someone_invited_you_as_admin: "Jemand hat dich als Admin von %{application} eingeladen, du kannst die Einladung über den untenstehenden Link akzeptieren."
      someone_invited_you_as_private_user: "Jemand hat dich als private_user von %{application} eingeladen, du kannst die Einladung über den folgenden Link akzeptieren."
    password_change: 
      greeting: "Hallo %{recipient}!"
      message: "Wir kontaktieren dich, um dich darüber zu informieren, dass dein Passwort geändert wurde."
      subject: "Passwort geändert"
    reset_password_instructions: 
      action: "Mein Passwort ändern"
      greeting: "Hallo %{recipient}!"
      instruction: "Jemand hat einen Link angefordert, um dein Passwort zu ändern. Falls du das selbst warst, dann folge diesem Link:"
      instruction_2: "Falls du das nicht selbst warst, kannst du diese E-Mail ignorieren."
      instruction_3: "Dein Passwort ändert sich erst, wenn du auf den obigen Link zugreifst und ein neues Passwort erstellst."
    unlock_instructions: 
      action: "Entsperre mein Konto"
      greeting: "Hallo %{recipient}!"
      instruction: "Klicke auf den folgenden Link, um dein Konto zu entsperren:"
      message: "Dein Konto wurde aufgrund einer übermässigen Anzahl fehlgeschlagener Anmeldeversuche gesperrt."
```

**Comment by Naadjjaa** [comment]
So werden aber noch immer nicht alle Mails richtig übersetzt. Das File enthielt alles nur Texte aus Notifications.
![image](https://user-images.githubusercontent.com/75797851/195097126-fd9516e9-c9dc-4177-b6a0-a4622ee0b227.png)

**Comment by Naadjjaa** [comment]
![image](https://user-images.githubusercontent.com/75797851/223374004-497227bd-1cd9-46c4-a4fa-c9870c5b63bb.png)
Hier noch ein Beispiel

**Comment by Kagemaru** [comment]
Hmm, TermCustomizer greift einfach nicht bei den Mails.
Soll ich die Übersetzungen in den deutschen locales aufnehmmen?
Das ändert es dann für alle. Auf [mein Issue](https://github.com/mainio/decidim-module-term_customizer/issues/93) bezüglich den Devise mails gab es noch keine Reaktion.

**Comment by Naadjjaa** [comment]
@Kagemaru habe die Übersetzungen per Mail geschickt

**Comment by Kagemaru** [comment]
@Naadjjaa
Wie in meinem vorigen Post beschrieben, greifen diese Änderungen für alle Tenants. Trotzdem ist mir nun, nach der Hälfte der ausgeführten Arbeit, aufgefallen, dass die bereitgestellten Übersetzungen voll sind mit Dialog Luzern spezifischen Texten.

Ich habe das Gefühl, dass kann nicht richtig sein.

**Comment by Naadjjaa** [comment]
@Kagemaru @bsantschi Dann habe ich aber ein grosses Problem, weil es kann nicht sein, dass Leute diese E-Mail erhalten, wenn wir eine Schadenmeldung beantworten.

Die Wörter "Vorschlag" und "akzeptiert" müssen zwingend ersetzt werden.
Ich habe sie umbenannt in "Beitrag" und "beantwortet" - extra Wörter, die neutral und vielseitig einsetzbar sind.

Über alles andere können wir diskutieren aber diese beiden Wörter brauche ich zwingend für den Launch. 

![image](https://github.com/stadtluzern/decidim-ocl/assets/75797851/dac5a993-a09e-4801-b220-980998070980)

**Comment by carlobeltrame** [comment]
Ich habe die Liste der Übersetzungen nie bekommen. Die zwei Wörter müssten jedenfalls, um konsistent zu sein, in weitaus mehr als nur diesem einen E-Mail-Text angepasst werden. Ähnliche (aber nicht deckungsgleiche) Mails gehen an die Autoren und die Followers eines Vorschlags oder einer Schadensmeldung, und ex sind unterschiedliche Mailtexte wenn ein Vorschlag/Schadensmeldung in Bearbeitung ist, akzeptiert wird oder abgelehnt wird. Das sind also schon mal mindestens 6 E-Mails, und wir müssen jeweils Betreff, Textkörper und "Outro" (Sie haben diese Benachrichtigung erhalten, weil...) anpassen.

<details>
 <summary>Der Vollständigkeit halber ist hier aufklappbar die Liste mit allen E-Mail Notification Texten aus dem Decidim Proposals Modul. Theoretisch müssten sämtliche diese Übersetzungen angepasst werden, um konsistent zu sein.</summary>

```yml
admin:
  proposal_note_created:
    email_intro: Jemand hat eine Notiz zum Vorschlag "%{resource_title}" hinterlassen. Schauen Sie sich diese im <a href="%{admin_proposal_info_url}">Admin-Panel</a> an
    email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie diesen Vorschlag bewerten können.
    email_subject: Jemand hat eine Notiz für Vorschlag %{resource_title} erstellt.
    notification_title: Jemand hat eine Notiz für den Vorschlag <a href="%{resource_path}">%{resource_title}</a>erstellt. Sie können sie über das <a href="%{admin_proposal_info_path}">Admin-Panel</a> anzeigen
collaborative_draft_access_accepted:
  email_subject: "%{requester_name} wurde zur Mitwirkung an %{resource_title} akzeptiert."
  notification_title: <a href="%{requester_path}">%{requester_name} %{requester_nickname}</a> wurde zur Mitwirkung am kollaborativen Entwurf <a href="%{resource_path}">%{resource_title}</a> <strong>angenommen</strong>.
collaborative_draft_access_rejected:
  email_subject: "%{requester_name} wurde als Mitwirkender des kollaborativen Entwurfs %{resource_title} abgelehnt."
  notification_title: <a href="%{requester_path}">%{requester_name} %{requester_nickname}</a> wurde als Mitwirkender beim kollaborativen Entwurf <a href="%{resource_path}">%{resource_title}</a> <strong>abgelehnt</strong>.
collaborative_draft_access_requested:
  email_subject: "%{requester_name} hat um Zugang zur Mitwirkung bei %{resource_title} angefragt."
  notification_title: <a href="%{requester_path}">%{requester_name} %{requester_nickname}</a> hat Zugriff beantragt, um beim kollaborativen Entwurf <a href="%{resource_path}">%{resource_title}</a> mitzuwirken. Bitte <strong>den Antrag akzeptieren oder ablehnen</strong>.
collaborative_draft_access_requester_accepted:
  email_subject: Sie wurden als Mitwirkender von %{resource_title} angenommen.
  notification_title: Sie wurden zur Mitwirkung am kollaborativen Entwurf <a href="%{resource_path}">%{resource_title}</a> <strong>akzeptiert</strong>.
collaborative_draft_access_requester_rejected:
  email_subject: Sie wurden als Mitwirkender von %{resource_title} abgelehnt.
  notification_title: Sie wurden als Mitwirkender beim kollaborativen Entwurf <a href="%{resource_path}">%{resource_title}</a> <strong>abgelehnt</strong>.
collaborative_draft_withdrawn:
  email_subject: "%{author_name} %{author_nickname} hat den kollaborativen Entwurf %{resource_title} zurückgezogen."
  notification_title: <a href="%{author_path}">%{author_name} %{author_nickname}</a> hat den kollaborativen Entwurf <a href="%{resource_path}">%{resource_title}</a> <strong>zurückgezogen</strong>.
creation_enabled:
  email_intro: 'Sie können jetzt neue Vorschläge in %{participatory_space_title} erstellen! Beteiligen Sie sich auf dieser Seite:'
  email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie %{participatory_space_title} folgen. Falls Sie keine solchen Benachrichtigungen mehr erhalten möchten, besuchen Sie den obigen Link.
  email_subject: In %{participatory_space_title} sind jetzt Vorschläge verfügbar
  notification_title: Sie können jetzt <a href="%{resource_path}">neue Vorschläge</a> in <a href="%{participatory_space_url}">%{participatory_space_title}</a> erfassen
endorsing_enabled:
  email_intro: 'Sie können Vorschläge in %{participatory_space_title} unterstützen! Beteiligen Sie sich auf dieser Seite:'
  email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie %{participatory_space_title} folgen. Falls Sie keine solchen Benachrichtigungen mehr erhalten möchten, besuchen Sie den obigen Link.
  email_subject: In %{participatory_space_title} ist es jetzt möglich, Vorschläge zu unterstützen
  notification_title: Sie können nun Vorschläge in <a href="%{participatory_space_url}">%{participatory_space_title}</a> <a href="%{resource_path}">unterstützen</a>
proposal_accepted:
  affected_user:
    email_intro: 'Ihr Vorschlag "%{resource_title}" wurde angenommen. Sie können die Antwort auf dieser Seite lesen:'
    email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie ein Autor von "%{resource_title}" sind.
    email_subject: Ihr Vorschlag wurde angenommen
    notification_title: Ihr Vorschlag <a href="%{resource_path}">%{resource_title}</a> wurde angenommen.
  follower:
    email_intro: 'Der Vorschlag "%{resource_title}" wurde akzeptiert. Sie können die Antwort auf dieser Seite lesen:'
    email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie "%{resource_title}" folgen. Falls Sie keine solchen Benachrichtigungen mehr erhalten möchten, besuchen Sie den obigen Link.
    email_subject: Ein Vorschlag, dem Sie folgen, wurde akzeptiert
    notification_title: Der Vorschlag <a href="%{resource_path}">%{resource_title}</a> wurde angenommen.
proposal_evaluating:
  affected_user:
    email_intro: 'Ihr Vorschlag "%{resource_title}" wird derzeit geprüft. Das Resultat wird auf dieser Seite aufgeschaltet werden:'
    email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie ein Autor von "%{resource_title}" sind.
    email_subject: Ihr Vorschlag wird evaluiert
    notification_title: Ihr Vorschlag <a href="%{resource_path}">%{resource_title}</a> wird evaluiert.
  follower:
    email_intro: 'Der Vorschlag "%{resource_title}" wird derzeit geprüft. Das Resultat wird auf dieser Seite aufgeschaltet werden:'
    email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie "%{resource_title}" folgen. Falls Sie keine solchen Benachrichtigungen mehr erhalten möchten, besuchen Sie den obigen Link.
    email_subject: Ein Vorschlag, dem Sie folgen, wird evaluiert
    notification_title: Der Vorschlag <a href="%{resource_path}">%{resource_title}</a> wird evaluiert.
proposal_mentioned:
  email_intro: Ihr Vorschlag "%{mentioned_proposal_title}" wurde <a href="%{resource_url}">hier</a> in den Kommentaren erwähnt.
  email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie ein Autor von "%{resource_title}" sind.
  email_subject: Ihr Vorschlag "%{mentioned_proposal_title}" wurde erwähnt
  notification_title: Ihr Vorschlag "%{mentioned_proposal_title}" wurde <a href="%{resource_path}">hier</a> in den Kommentaren erwähnt.
proposal_published:
  email_intro: '%{author_name} %{author_nickname}, dem Sie folgen, hat einen neuen Vorschlag mit dem Namen "%{resource_title}" veröffentlicht. Sehen Sie es sich an und reden Sie mit:'
  email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie %{author_nickname} folgen. Falls Sie keine solchen Benachrichtigungen mehr erhalten möchten, besuchen Sie den obigen Link.
  email_subject: Neuer Vorschlag "%{resource_title}" von %{author_nickname}
  notification_title: Der Vorschlag <a href="%{resource_path}">%{resource_title}</a> wurde von <a href="%{author_path}">%{author_name} %{author_nickname}</a> veröffentlicht.
proposal_published_for_space:
  email_intro: Der Vorschlag "%{resource_title}" wurde zu "%{participatory_space_title}" hinzugefügt, welchem Sie folgen.
  email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie "%{participatory_space_title}" folgen. Sie können den Erhalt von Benachrichtigungen über den vorherigen Link beenden.
  email_subject: Neuer Vorschlag "%{resource_title}" zu %{participatory_space_title} hinzugefügt
proposal_rejected:
  affected_user:
    email_intro: 'Ihr Vorschlag "%{resource_title}" wurde abgelehnt. Sie können die Antwort auf dieser Seite lesen:'
    email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie ein Autor von "%{resource_title}" sind.
    notification_title: Ihr Vorschlag <a href="%{resource_path}">%{resource_title}</a> wurde abgelehnt.
  follower:
    email_intro: 'Der Vorschlag "%{resource_title}" wurde abgelehnt. Sie können die Antwort auf dieser Seite lesen:'
    email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie "%{resource_title}" folgen. Falls Sie keine solchen Benachrichtigungen mehr erhalten möchten, besuchen Sie den obigen Link.
    email_subject: Ein Vorschlag, dem Sie folgen, wurde abgelehnt
    notification_title: Der Vorschlag <a href="%{resource_path}">%{resource_title}</a> wurde abgelehnt.
proposal_update_category:
  email_intro: 'Ein Administrator hat die Kategorie Ihres Vorschlags "%{resource_title}" aktualisiert, sehen Sie es sich an:'
  email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie der Autor des Vorschlags sind.
  email_subject: Die Vorschlagskategorie %{resource_title} wurde aktualisiert
  notification_title: Die Vorschlagskategorie <a href="%{resource_path}">%{resource_title}</a> wurde von einem Administrator aktualisiert.
proposal_update_scope:
  email_intro: 'Ein Administrator hat den Bereich Ihres Vorschlags „%{resource_title}“ aktualisiert, sehen Sie es sich das auf dieser Seite an:'
  email_outro: Sie haben diese Benachrichtigung erhalten, weil Sie der Autor des Vorschlags sind.
  email_subject: Der Bereich des Vorschlags %{resource_title} wurde aktualisiert
  notification_title: Der Bereich des Vorschlags <a href="%{resource_path}">%{resource_title}</a> wurde von einem Administrator aktualisiert.
```
</details>

@Naadjjaa möchtest du dass ich...
a) nur das eine E-Mail aus deinem Screenshot anpasse?
b) die 6 oben erwähnten ähnlichen E-Mails anpasse?
c) alle oben aufklappbaren E-Mail-Texte anpasse?

Je mehr ich anpasse, desto mehr Auswirkungen hat das dann halt auch auf die anderen Tenants.
