### ISSUE TITLE
Default Bild bei Organisationen

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#63]
Wenn eine Organisation kein Bild hochlädt, sieht das etwas blöd aus in der Organisationsübersicht. Können wir hier ein Standard Defaultbild einsetzten, falls keines hinzugefügt wird?

**Comment by Kagemaru** [comment]
Mit etwas CSS Magie, könnte man das Placement vereinheitlichen. Ist dann halt spezifisch auf die grössten Bilder ausgelegt und sieht komisch aus, wenn es keine Bilder in einer Zeile hat oder ein Bild nicht die volle Höhe hat (z.B. Franco Luzern).

Was meint ihr dazu?

<details>
<summary>Vorher</summary>

![before_css_shenanigans](https://user-images.githubusercontent.com/12155/112822067-bbc27480-9087-11eb-811c-9444a908ea5f.png)
</details>

<details>
<summary>Nachher</summary>

![after_css_shenanigans](https://user-images.githubusercontent.com/12155/112822193-ea404f80-9087-11eb-8409-12ba36bb8ebf.png)
</details>

**Comment by Naadjjaa** [comment]
Danke @Kagemaru. Ich finde es sieht nachher besser aus. 
Meine Ursprungsfrage war hier, ein Default-Bild hochladen zu können. Dass wenn eine Organisation nichts hochlädt, ein von uns definiertes Bild angezeigt wird. Geht das?

**Comment by Kagemaru** [comment]
Da die Assemblies mit einer Standard cell view von Decidim gerendert werden, bedeutet dies einen grösseren Eingriff in die Standarddarstellung von Decidim. Wir überschreiben damit ein zentrales Template von Decidim.

Wenn ihr mir aber ein Default Bild geben könnt, dass ich in unsere Assets packen kann, könnte ich es trotzdem mit CSS lösen.

Hier als Beispiel die Musikschule mit dem festen Logo der Sportstadt Luzern):
![image](https://user-images.githubusercontent.com/12155/120205730-9807e000-c22a-11eb-8979-91c418702dad.png)

```css
.card__content::before {
  content: '';
  height: 160px;
  width: 378px;
  display: block;
  background-image: url(http://localhost:3000/uploads/decidim/assembly/hero_image/15/Querformat.png);
  margin: -1.5rem 0 1.5rem -1.5rem;
  background-position: center;
  background-size: cover;
  position: relative;
}

a + .card__content::before {
  display: none;
}
```
